<?php
namespace backend\controllers;

use yii\web\Controller;
/**
 * Site controller
 */
class CommonController extends Controller
{
    public $user_id = 0;
    public $user_name = '';
    //是否是超级管理员用户组内用户
    public $is_super_manager = false;

    //是否是门店管理员
    public $is_store_manager_id = false;

    public $is_need_login = true;
    protected $ignore_action = '';

    /**
     * 用户模型
     * @var \common\models\SysManager
     * */
    public $user_model=null;

    /**
     *
     * @var \yii\web\Request
     * */
    public $request;


    public function init()
    {
        $this->request = \Yii::$app->request;

        $user_info = \Yii::$app->session->get('user_info');
        if(!empty($user_info)){
            $this->user_id = empty($user_info['user_id'])?0:$user_info['user_id'];
            $this->is_super_manager = empty($user_info['is_super_manager'])?false:true;

            $this->user_model = \common\models\SysManager::find()
                ->with(['linkRole.linkParentRoles'])
                ->where(['id'=>$this->user_id])
                ->one();
            //门店角色
            if($this->user_model['linkRole']['id']==2 || $this->user_model['linkRole']['linkParentRoles']['id']==2 ){
                $this->is_store_manager_id = $this->user_model['id'];
            }

            //禁用session
            if(empty($this->user_model) || $this->user_model['status']!=1){
                $this->user_id = 0;
                \Yii::$app->session->destroy();
            }

        }

        return parent::init();
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action);

        if(!$this->user_id && strpos($this->ignore_action,$action->id)===false){
            if($this->request->isAjax){
                //需要登录才能访问
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                \Yii::$app->response->data = array(
                    'code' => 0,
                    'msg' => '请先登录',
                    'url' => \yii\helpers\Url::to(['index/login'])
                );
                return false;
            }else{
                //需要登录才能访问
                $this->redirect(\yii\helpers\Url::to(['index/login']));
                return false;
            }
        }

        return true; // TODO: Change the autogenerated stub
    }



}
