<?php

namespace frontend\controllers;

//各种文章
class ArticleController extends CommonController
{

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        $nav_prop = \common\models\SysNavPage::getPropInfo('nav_prop');
        $mer = [];
        foreach ($nav_prop as $key=>$vo){
            if(!isset($vo['article_info'])){
                continue;
            }
            $article_info = $vo['article_info'];
            if(isset($article_info['type'])){
                $type = $article_info['type'];
                $mer[$type]['class']  = !empty($article_info['class'])?$article_info['class']:'frontend\components\ArticleAction';
                $mer[$type]['con_type']  = $key;//文章类型
                !empty($type) && $mer[$type]['type']  = $type;
                !empty($article_info['page_temp']) && $mer[$type]['page_temp']  = $article_info['page_temp']; //页面模版
            }
        }

        $actions = array_merge($actions,$mer);
        return $actions;
    }


    public function actionIndex()
    {
        return $this->render('index', [

        ]);
    }

    //列表
    public function actionShowList()
    {
        $id = $this->request->get('id',0);

        $query = \common\models\Article::find()->where(['cid'=>$id,'status'=>1]);
        $count = $query->count();
        $pagination = \Yii::createObject(array_merge(\Yii::$app->components['pagination'],['totalCount' => $count]));
        $list = $query
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->orderBy('addtime desc')
            ->all();

        $data = [];

        foreach($list as $vo){
            $info = [
                'id'         =>  $vo['id'],
                'cid'         =>  $vo['cid'],
                'title'      =>  $vo['title'],
                'image'      =>  $vo['image'],
                'addtime'    =>  $vo['addtime']?date('Y-m-d',$vo['addtime']):'',
                'visit'      =>  $vo['visit'],
                'desc'       =>  $vo['desc'],
            ];

            $data[] = $info;
        }

        return $this->asJson(['code'=>1,'msg'=>'获取成功','data'=>$data,'page'=>$pagination->pageCount]);
    }

    //详情
    public function actionDetail()
    {
        $menu_id = $this->request->get('menu_id',0);
        $id = $this->request->get('id',0);
        $con_type = $this->request->get('con_type',0);

        //获取案例所有栏目
        $menu = \common\models\SysNavPage::find()->with(['linkNavPage' => function ($query) {
            return $query->where(['status' => 1]);
        }])->asArray()->where(['pid' => 0, 'status' => 1, 'type' => $con_type])->one();
        $ch_title = '';//副标题
        $meta_key = $menu['key'];
        $meta_desc = $menu['desc'];
        foreach ($menu['linkNavPage'] as $vo){
            if($vo['id']==$menu_id){
                $ch_title = $vo['name'];
                $meta_key = $vo['key'];
                $meta_desc = $vo['desc'];
                break;
            }
        }

        $model = \common\models\Article::find()->where(['id'=>$id,'status'=>1])->one();
        return $this->render('detail',[
            'menu_id' => $menu_id,
            'model' => $model,
            'menu' => $menu,
            'title' => $menu['name'],
            'ch_title' => $ch_title,
            'meta_key'=>$meta_key,
            'meta_desc'=>$meta_desc,
        ]);
    }
}