<?php
namespace frontend\controllers;


use yii\web\Controller;

class CommonController extends Controller
{
    public $user_id = 6806;

    public $is_need_login = false;
    protected $ignore_action = '';


    /**
     *
     * @var \yii\web\Request
     * */
    public $request;


    public function init()
    {
        $this->request = \Yii::$app->request;

        $user_info = \Yii::$app->session->get('user_info');
        if(!empty($user_info)){
            $this->user_id = empty($user_info['user_id'])?0:$user_info['user_id'];


        }

        return parent::init();
    }

    public function beforeAction($action)
    {
        parent::beforeAction($action);
        if($this->is_need_login){
            if(!$this->user_id && strpos($this->ignore_action,$action->id)===false){
                if($this->request->isAjax){
                    //需要登录才能访问
                    \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    \Yii::$app->response->data = array(
                        'code' => 0,
                        'msg' => '请先登录',
                        'url' => \yii\helpers\Url::to(['index/login'])
                    );
                    return false;
                }else{
                    //需要登录才能访问
                    $this->redirect(\yii\helpers\Url::to(['index/login']));
                    return false;
                }
            }
        }


        return true; // TODO: Change the autogenerated stub
    }


}