<?php
namespace common\models;


use common\models\use_traits\SoftDelete;

class UserBankCard extends BaseModel
{
    use SoftDelete;
    public static $fields_status = ['申请中','已发放','拒绝'];
    public static function tableName()
    {
        return '{{%user_bank_card}}';
    }

    public function attributeLabels()
    {
        return [
            'name' => '开户银行',
            'number' => '银行卡号',
            'phone' => '手机号',
            'username' => '银行户主',
        ];
    }


    public function rules()
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub
        $rules = array_merge($rules,[
            ['uid','default','value'=>0],
        ]);
        $rules = array_merge($rules,[
            [['name','number','phone','username'],'required','message'=>'{attribute}必须输入'],
            ['phone','match','pattern'=>'/^1[0-9]{10}$/','message'=>'请输入正确的手机号码'],
            ['number','match','pattern'=>'/^[0-9a-zA-Z]+$/','message'=>'请输入正确的银行卡号'],

        ]);
        return $rules;
    }

}